### PR TITLE
GraphStage rewrite

### LINKED ISSUE #21: Replace deprecated ActorPublisher with GraphStage
http://doc.akka.io/docs/akka/current/scala/project/migration-guide-2.4.x-2.5.x.html#deprecation-of-actorsubscriber-and-actorpublisher

### PR DESCRIPTION
**Pull request by gafiatulin**
Fixes #21

### CODE REVIEW

**Comment by savulchik** [comment]
@gafiatulin thanks for contributing! I will give you feedback soon)

**Comment by savulchik** [comment]
@gafiatulin I'd like to cherry-pick library updates and cross building into master in order to release `0.3.0` version of the library having `ActorPublisher` implementation. After that I'd ask you to rebase `GraphStage` implementation on updated master.

BTW, don't you mind to split the latest commit into another PR? I'd like to discuss the approach of using typeclasses like `Unmarshaller[A]` for abstracting over return type.

**Comment by savulchik** [comment]
@gafiatulin I released `0.3.0` version, now you may rebase your branch on master

**Comment by gafiatulin** [comment]
@savulchik I rebased on current master.
Also dropped polymorphic source commit. Going to open new issue concerning that in a minute.

**Comment by gafiatulin** [comment]
#23 is what I was looking for in the first place with that polymorphic source commit. I did it that way because it requires changes in interactions with underlying jeromq (`ZMsg.recvMsg(s)` vs  `s.recv`).

Not really sure about unmarshalling being done in source. Sources shouldn't be concerned with deserializing of incoming data into domain entities.  Especially not with my initial approach.

**Pull request closed without merging**
